version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./resources/mysql:/var/lib/mysql
    networks:
      - lumen

  app:
    build: .
    container_name: app
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - lumen

networks:
  lumen:
